#include "include/camera_controller.h"
#include "include/camera.h"
#include "include/component.h"
#include "include/fps_counter.h"
#include "include/game_object.h"
#include "include/glsl_shader.h"
#include "include/image.h"
#include "include/input.h"
#include "include/material.h"
#include "include/mesh.h"
#include "include/mesh_renderer.h"
#include "include/OBJ_Loader.h"
#include "include/render_component.h"
#include "include/renderer.h"
#include "include/resource.h"
#include "include/resource_manager.h"
#include "include/rid.h"
#include "include/stb_image.h"
#include "include/stb_image_write.h"
#include "include/transform.h"
#include "include/utils.h"
#include "include/window.h"
extern Renderer* renderer;
extern Input* input;
extern ResourceManager* resourceManager;
